language : java

jdk :
  - openjdk8

branches: #Travis CI를 어느 branch 가 푸시될 때 수행할 것인지 지정 (master branch 만 수행할 것)
  only:
    - master

#before_install : 프로젝트 내 gradlew 파일 실행권한 부여
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache :
  directories:
    -  '$Home/.m2/repository'
    -  '$Home/.gradle'


#scropt: master branch 에 푸시되었을 때 수행하는 명령어 - gradlew 를 통해 clean&build 수행
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - sohnyj37@gmail.com