language : java

jdk :
  - openjdk8

branches: #Travis CI를 어느 branch 가 푸시될 때 수행할 것인지 지정 (master branch 만 수행할 것)
  only:
    - master

#before_install : 프로젝트 내 gradlew 파일 실행권한 부여
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache :
  directories:
    -  '$Home/.m2/repository'
    -  '$Home/.gradle'

#빌드시 만들어지는 jar 파일을 S3와 연동
before_deploy:
  - zip -r springboot-webservice * #현재 위치의 모든파일(*) 을 springboot-webservice 이름으로 압축
  - mkdir -p deploy #Travis CI가 실행중인 위치에서 deploy 디렉토리 생성
  - mv springboot-webservice.zip deploy/springboot-webservice.zip #압축파일을 deploy 디렉토리 하위로 이동

deploy:
  - provider : s3
    access_key_id : $AWS_ACCESS_KEY #travis repo setting에 설정되어있는 key 값
    secret_access_key : $AWS_SECRET_KEY #travis repo setting에 설정되어있는 secret값
    bucket : tuninghour-springboot-build #연결할 S3 버킷 명
    region : ap-northeast-2
    skip_cleanup : true
    acl: private #zip 파일 접근을 private로
    local_dir: deploy #before_deploy  에서 생성한 디렉토리
    wait-until-deployed : true



#scropt: master branch 에 푸시되었을 때 수행하는 명령어 - gradlew 를 통해 clean&build 수행
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - sohnyj37@gmail.com